install xmllint

diff --git a/.github/workflows/tf-module-base.yml b/.github/workflows/tf-module-base.yml
--- a/.github/workflows/tf-module-base.yml
+++ b/.github/workflows/tf-module-base.yml
@@ -269,15 +269,16 @@ jobs:
       - name: Summarize Checkov Report
         id: checkov_summary
         run: |
+          sudo apt-get update && sudo apt-get install -y libxml2-utils
           CHECKOV_FAILED=$(xmllint --xpath 'string(//testsuites/@failures)' checkov-report.xml)
-            echo "Failed checks: $CHECKOV_FAILED"
-            if [[ "$CHECKOV_FAILED" == "0" ]]; then
-              echo "checkov_status=success" >> $GITHUB_ENV
-            else
-              echo "checkov_status=failed" >> $GITHUB_ENV
-              exit 1
-            fi          
-            
+          echo "Failed checks: $CHECKOV_FAILED"
+          if [[ "$CHECKOV_FAILED" == "0" ]]; then
+            echo "checkov_status=success" >> $GITHUB_ENV
+          else
+            echo "checkov_status=failed" >> $GITHUB_ENV
+            exit 1
+          fi          
+
   consume_outputs:
     needs: [terraform_fmt, terraform_docs, terraform_lint, terraform_trivy, terraform_checkov]
     runs-on: ubuntu-latest
